[package]
name = "slog-syslog"
version = "0.11.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Syslog drain for slog-rs"
keywords = ["slog", "logging", "json", "log", "syslog"]
license = "MPL-2.0"
documentation = "https://docs.rs/slog-rs/term"
homepage = "https://github.com/slog-rs/slog"
repository = "https://github.com/slog-rs/syslog"
readme = "README.md"

[lib]
path = "lib.rs"

[dependencies]
slog = "2"
syslog = "3.2.0"
nix = "0.9.0"
